name: Get version test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get version
        id: version-step
        uses: michmich112/extract-version@gha-stats-v0.0.10
        with:
          version-file: VERSION
          schema: major.minor.build
      - name: test
        run: |
          echo "version -> $VERSION"
        env:
          VERSION: ${{ steps.version-step.outputs.version }}
